server:
  port: 8080

logging:
  level:
    root: info
    org.springframework: info



spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SYS_AUTH?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    hikari: # 配置详情 https://github.com/brettwooldridge/HikariCP
      connection-timeout: 20000
      minimum-idle: 5  # 最小空闲连接数量
      maximum-pool-size: 15 # 连接池最大连接数，默认是10
      idle-timeout: 10000 # 空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 1000 # # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      auto-commit: true
      pool-name: UaaCP
      connection-test-query: SELECT 1